#!/bin/sh
### BEGIN INIT INFO
# Provides:          zte
# required-start:
# required-stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: late daemons
# Description:       late daemons
### END INIT INFO

. /lib/init/vars.sh
. /lib/lsb/init-functions

# Default variables
ROOT=/opt/late
DEV="Telnet 10.46.74.82 10006"
LATE="python late.py $DEV"

LOG="/var/log/late"

# export PATH="${PATH:+$PATH:}/opt/late"
# export PYTHONPATH=$PATH

start() {
  mkdir -p $LOG
  cd $ROOT
  nohup $LATE >${LOG:+$LOG/}late.out 2>&1 &
}

stop() {
  pkill -f "$LATE"  
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}" >&2
    exit 3
    ;;
esac

exit 0
