#!/bin/sh
### BEGIN INIT INFO
# Provides:          zte
# required-start:
# required-stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: late daemons
# Description:       late daemons
### END INIT INFO

. /lib/init/vars.sh
. /lib/lsb/init-functions

# Default variables
ROOT="/opt/late"
DEV="Telnet 10.46.74.82 10006"
LATE="python main.py $DEV"

cd $ROOT

case "$1" in
  start)
    nohup $LATE &
    ;;
  stop)
    pkill -f "$LATE"
    ;;
  restart)
    pkill -f "$LATE"
    nohup $LATE &
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}" >&2
    exit 3
    ;;
esac

exit 0
